# See https://lefthook.dev/configuration/

pre-commit:
  jobs:
    - name: linters
      group:
        parallel: true
        jobs:
          - name: editorconfig
            run: go tool task lint:editorconfig -- {staged_files}

          # FIXME: Hangs when run.
          # - name: awesome-lint
          #   run: go tool task lint:awesome-lint -- {staged_files}

pre-push:
  jobs:
    - name: check-links
      glob: "*.md"
      run: go tool task lint:links -- {files}
