# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - lint

  lint:
    desc: Run all linters.
    deps:
      - lint:editorconfig
      - lint:links
      - lint:awesome-lint

  lint:awesome-lint:
    desc: Run the linter for awesome lists.
    cmd: npx awesome-lint README.md README_ZH.md

  lint:editorconfig:
    desc: Check that files conform to editorconfig rules.
    cmd: go tool editorconfig-checker .

  lint:links:
    desc: Check for broken links. Update any permanent-redirects.
    cmd: |
        go tool xurls *.md \
        | sort -u \
        | gawk '!/(instagram|linkedin|twitter|marketplace.visualstudio).com|bsky.app/' \
        | go tool xurls -fix
